using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class pausescreen : MonoBehaviour
{
    GameObject[] pauseObjects;
    private GameObject task;

    void Start()
    {
        task = GameObject.Find("task");
        Time.timeScale = 1;
        pauseObjects = GameObject.FindGameObjectsWithTag("ShowOnPause");
        hidePaused();
    }

    // Update is called once per frame
    void Update()
    {
        //uses the p button to pause and unpause the game
        if (Input.GetKeyDown(KeyCode.P))
        {
            if (Time.timeScale == 1)
            {
                Time.timeScale = 0;
                showPaused();
            }
            else if (Time.timeScale == 0)
            {
                Time.timeScale = 1;
                hidePaused();
            }
        }
        if (Input.GetKeyDown(KeyCode.Q))
        {
            Time.timeScale = 1;
            task.SendMessage((string)"Restart");
        }
    }

    public void showPaused()
    {
        foreach (GameObject g in pauseObjects)
        {
            g.SetActive(true);
        }
    }

    public void hidePaused()
    {
        foreach (GameObject g in pauseObjects)
        {
            g.SetActive(false);
        }
    }
}
